// HolyChildhood/client/src/components/Home.tsx
import React, {useContext, useEffect} from 'react';
import makeStyles from "@material-ui/core/styles/makeStyles";
import alter from "../images/alter.jpg";
import Typography from '@material-ui/core/Typography';
import Grid from "@material-ui/core/Grid";
import AppState from "../stores/AppState";
import {TextContent} from "../models/PageContent";
import {Event} from "../models/Calendar";
import TextContentControl from "./content/TextContentControl";
import past2future from "../images/Past2Future.jpg";

const style = makeStyles(theme => ({
    image: {
        backgroundImage: `url(${alter})`,
        height: "225px",
        backgroundSize: "cover",
        backgroundPosition: "center 59.85%",
    },
    quoteContainer: {
        height: "100%",
        position: "relative"
    },
    quote: {
        position: "absolute",
        top: "35%",
        left: "5%",
        right: "auto",
        bottom: "auto",
        backgroundColor: 'rgba(0,0,0,0.4)',
        width: "400px",
        margin: 0,
        padding: "10px",
        borderRadius: "10px",
        wordWrap: "break-word",
        textAlign: "left",
        fontFamily: "inherit",
        color: '#fff',
        [theme.breakpoints.down('sm')]: {
            width: "75%"
        },
    }
}));


function Home() {
    const classes = style();
    const store = useContext(AppState);
    const { getTextContent } = store.domainStore.contentStore;
    const { getUpcomingEvents } = store.domainStore.eventStore;

    const [mainContent, setMainContent] = React.useState<TextContent | null>(null);
    const [scheduleContent, setScheduleContent] = React.useState<TextContent | null>(null);
    const [contactContent, setContactContent] = React.useState<TextContent | null>(null);
    const [events, setEvents] = React.useState<Event[]>([]);

    useEffect(() => {
        getTextContent(1).then((content) => {
            setMainContent(content);
        });
        getTextContent(2).then((content) => {
            setScheduleContent(content);
        });
        getTextContent(3).then((content) => {
            setContactContent(content);
        });
        getUpcomingEvents(8).then((events) => {
            setEvents(events);
        });
    }, [getTextContent, getUpcomingEvents])

    return(
        <div>
            <div className={classes.image}>
                <div className={classes.quoteContainer}>
                    <Typography className={classes.quote}>
                        At Holy Childhood, we use the gifts that God has given us, our gifts of time, talent and treasure, to further the Kingdom of God here on earth.
                    </Typography>
                </div>
            </div>
            <Grid container direction="column" style={{padding: "30px"}} spacing={4}>
                <Grid item>
                    <Typography variant="h2" style={{marginBottom: ".5rem" }}>
                        Our Mission
                    </Typography>
                    <Typography variant="body1">
                        To be a credible sign of God’s love and care, Holy Childhood Parish needs to be a loving, charitable and caring community that is spiritually challenging, generously welcoming and liturgically alive. We strive to reach out to those in spiritual need and basic material needs. We will be open to the ideas of others, and, with God’s help, continue to live out the Gospel message.
                    </Typography>
                </Grid>
                <Grid item>
                    {mainContent &&
                        <TextContentControl content={mainContent} />
                    }
                </Grid>
                <Grid item>
                    <Grid container direction="row" spacing={4}>
                        <Grid item xs={8}>
                            {scheduleContent &&
                                <TextContentControl content={scheduleContent} />
                            }
                        </Grid>
                        <Grid item xs={4}>
                            <h2>Upcoming Events</h2>
                            {events.map(event => (
                                <div>
                                    {event.start} - {event.title}
                                </div>
                            ))}
                        </Grid>
                    </Grid>
                </Grid>
                <Grid item>
                    <Grid container direction="row" spacing={4}>
                        <Grid item xs={8}>
                            {contactContent &&
                                <TextContentControl content={contactContent} />
                            }
                        </Grid>
                        <Grid item xs={4}>
                            <a href="http://churchcampaign.org/holychild" target="_blank" rel="noopener noreferrer">
                                <img src={past2future} style={{width: 250}} alt="Past2Future" />
                            </a>
                        </Grid>
                    </Grid>
                </Grid>
            </Grid>
        </div>
    )
}

export default Home;

// HolyChildhood/ClientApp/src/app/home/home.component.ts
import { Component, OnInit } from '@angular/core';

import { TextContent} from '../shared/models/page-content';
import { PagesService } from '../pages/pages.service';
import { AuthService } from '../shared/services/auth.service';
import { EventService } from '../shared/services/event.service';
import { Event } from '../shared/models/calendar';

import * as moment from 'moment';

@Component({
    selector: 'app-home',
    templateUrl: './home.component.html',
    styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {

    main: TextContent;
    weeklySchedule: TextContent;
    contactInfo: TextContent;
    upcomingEvents: Event[];

    constructor(private authService: AuthService, private pagesService: PagesService, private eventService: EventService) {}

    ngOnInit(): void {
        this.getMainText();
        this.getWeeklyScheduleText();
        this.getContactInformationText();
        this.getUpcomingEvents();
    }

    isAuthenticated(): boolean {
        return this.authService.isLoggedIn();
    }

    isEditOn(): boolean {
        return this.isAuthenticated() && this.authService.isEdit();
    }

    getMainText(): void {
        this.pagesService.getTextContent(1).subscribe((data: TextContent) => {
            this.main = data;
        });
    }

    getWeeklyScheduleText(): void {
        this.pagesService.getTextContent(2).subscribe((data: TextContent) => {
            this.weeklySchedule = data;
        });
    }

    getContactInformationText(): void {
        this.pagesService.getTextContent(3).subscribe((data: TextContent) => {
            this.contactInfo = data;
        });
    }

    getUpcomingEvents(): void {
        this.eventService.getUpcomingEvents(8).subscribe(events => {
            this.upcomingEvents = events;
        });
    }

    getDate(dateStr) {
        const date = moment(dateStr);
        return date.format('MMMM Do YYYY');
    }

    getTime(dateStr) {
        const date = moment(dateStr);
        return date.format('hh:mm a');
    }
}


<div class="hcc-inside-image">
    <div style="height: 100%; position: relative;">
        <p class="hcc-quote">
            At Holy Childhood, we use the gifts that God has given us, our gifts of time, talent and treasure, to further the Kingdom of God here on earth.
        </p>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col">
            <h2>Our Mission</h2>
            <p>
                To be a credible sign of God’s love and care, Holy Childhood Parish needs to be a loving, charitable and caring community that is spiritually challenging, generously welcoming and liturgically alive. We strive to reach out to those in spiritual need and basic material needs. We will be open to the ideas of others, and, with God’s help, continue to live out the Gospel message.
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div [ngClass]="{'edit': isEditOn()}">
                <app-content-text [textContent]="main"></app-content-text>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <h2>Weekly Schedule</h2>

            <div [ngClass]="{'edit': isEditOn()}">
                <app-content-text [textContent]="weeklySchedule"></app-content-text>
            </div>
            <!--<div class="row">-->
                <!--<div class="col"><b>Saturday</b></div>-->
            <!--</div>-->
            <!--<div class="row">-->
                <!--<div class="col">Reconciliation</div>-->
                <!--<div class="col">4:00 P.M.</div>-->
            <!--</div>-->
            <!--<div class="row">-->
                <!--<div class="col">Mass</div>-->
                <!--<div class="col">5:00 P.M.</div>-->
            <!--</div>-->
            <!--<div class="row">-->
                <!--<div class="col"><b>Sunday</b></div>-->
            <!--</div>-->
            <!--<div class="row">-->
                <!--<div class="col">Mass</div>-->
                <!--<div class="col">8:00 A.M.</div>-->
            <!--</div>-->
            <!--<div class="row">-->
                <!--<div class="col"></div>-->
                <!--<div class="col">10:30 A.M.</div>-->
            <!--</div>-->
            <!--<div class="row">-->
                <!--<div class="col"><b>Tue, Thurs, Fri</b></div>-->
            <!--</div>-->
            <!--<div class="row">-->
                <!--<div class="col">Daily Mass</div>-->
                <!--<div class="col">8:00 A.M.</div>-->
            <!--</div>-->

        </div>
        <div class="col-md-4">
            <h2>Upcoming Events</h2>
            <!--<div class="row" *ngFor="let event of eventService.events">-->
                <!--<div class="col-lg-3">-->
                    <!--<div class="card" style="width: 75px; padding: 0; margin-bottom: 5px; border-color: #1f3e65">-->
                        <!--<div class="card-header text-center" style="font-weight: bold; padding: 0; background-color: #1f3e65; color: white">-->
                            <!--{{ event.start | date:'MMM'}}-->
                        <!--</div>-->
                        <!--<div class="card-body text-center" style="font-weight: bold; padding: 0;">-->
                            <!--{{ event.start | date:'d'}}-->
                        <!--</div>-->
                    <!--</div>-->
                <!--</div>-->
                <!--<div class="col-lg-9">-->
                    <!--<div style="font-weight: bold">{{ event.title }}</div>-->
                    <!--{{ event.start | date: 'shortTime'}}-->
                <!--</div>-->
            <!--</div>-->
        </div>
    </div>
    <br/>
    <div class="row">
        <div class="col-md-8">
            <h2>Contact Information</h2>
            <div [ngClass]="{'edit': isEditOn()}">
                <app-content-text [textContent]="contactInfo"></app-content-text>
            </div>

            <!--<div class="row">-->
                <!--<div class="col-md-2">-->
                    <!--<span class="list-item">Pastor</span>-->
                <!--</div>-->
                <!--<div class="col-md-10">-->
                    <!--Reverend Paul R. Wienhoff - <a href="mailto:paul.wienhoff@holychildhoodchurch.com">paul.wienhoff@holychildhoodchurch.com</a>-->
                <!--</div>-->
            <!--</div>-->
            <!--<div class="row">-->
                <!--<div class="col-md-2">-->
                    <!--<span class="list-item">Permanent Deacon</span>-->
                <!--</div>-->
                <!--<div class="col-md-10">-->
                    <!--Daniel R. Cozzi - <a href="mailto:dan.cozzi@holychildhoodchurch.com">dan.cozzi@holychildhoodchurch.com</a>-->
                <!--</div>-->
            <!--</div>-->
            <!--<div class="row">-->
                <!--<div class="col-md-2">-->
                    <!--<span class="list-item">Church Address</span>-->
                <!--</div>-->
                <!--<div class="col-md-10">-->
                    <!--419 East Church Street, Mascoutah, IL 62258-->
                <!--</div>-->
            <!--</div>-->
            <!--<div class="row">-->
                <!--<div class="col-md-2">-->
                    <!--<span class="list-item">Phone</span>-->
                <!--</div>-->
                <!--<div class="col-md-10">-->
                    <!--618-566-2958-->
                <!--</div>-->
            <!--</div>-->
            <!--<div class="row">-->
                <!--<div class="col-md-2">-->
                    <!--<span class="list-item">Postal Address</span>-->
                <!--</div>-->
                <!--<div class="col-md-10">-->
                    <!--104 North Independence, Mascoutah, IL 62258-->
                <!--</div>-->
            <!--</div>-->
            <!--<div class="row">-->
                <!--<div class="col-md-2">-->
                    <!--<span class="list-item">General Information</span>-->
                <!--</div>-->
                <!--<div class="col-md-10">-->
                    <!--<a href="mailto:hcc@holychildhoodchurch.com">hcc@holychildhoodchurch.com</a>-->
                <!--</div>-->
            <!--</div>-->
        </div>
        <div class="col-md-4">
            <a href="http://churchcampaign.org/holychild" target="_blank">
                <img src="assets/images/Past2Future.jpg" style="width: 250px">
            </a>
        </div>
    </div>

</div>
